[project]
name = "mcp-agribalyse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "mcp[cli]>=1.9.0",
    "requests>=2.31.0",
]
